jsonsage:
  label: JsonSage
  permalink: /jsonsage
  description: JsonSage相关文章

json:
  label: JSON
  permalink: /json
  description: JSON数据处理相关文章

workflow:
  label: 工作流
  permalink: /workflow
  description: 工作流自动化相关文章

automation:
  label: 自动化
  permalink: /automation
  description: 自动化处理相关文章
