name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: |
          echo "Current directory: $(pwd)"
          ls -la
          npm ci
      
      - name: Create env.js
        run: |
          echo "module.exports = { DEEPSEEK_API_KEY: '${{ secrets.DEEPSEEK_API_KEY }}' };" > env.js
          echo "Created env.js:"
          cat env.js

      - name: Build website
        run: |
          echo "Building website..."
          npm run build
          echo "Build complete. Contents of build directory:"
          ls -la build/

      # Note: this is the key step for deployment
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'  # only deploy from main branch
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_message: Deploy website
          full_commit_message: |
            Deploy website
            
            Deployed from ${{ github.sha }}
            Triggered by ${{ github.event_name }}
